namespace: fahcsim
name: grafana_stack
version: 1.0.3
readme: README.md
authors:
  - Mischa Friegang mischatravis10@gmail.com
description: "Installs Grafana, Prometheus, Loki, Prometheus Node Exporter,\
             and Promtail on Debian based systems."
tags:
  - prometheus
  - grafana
  - loki
  - promtail
  - prometheus_node_exporter
  - monitoring
  - logging
  - ubuntu
  - debian
dependencies: {}
repository: https://github.com/fahcsim/grafana_stack_collection
documentation: https://github.com/fahcsim/grafana_stack_collection/README.md
license:
    - "MIT"
