- name: install unzip package
  ansible.builtin.apt:
    name: unzip
    state: present

- name: extract tarball
  ansible.builtin.unarchive:
    src: "https://github.com/grafana/loki/releases/download/v\
         {{  version  }}/loki-linux-amd64.zip"
    dest: /tmp
    remote_src: true
  tags:
    - loki
  changed_when: false

- name: create /opt/loki directory
  ansible.builtin.file:
    path: /opt/loki
    state: directory
    owner: root
    group: root
    mode: 0755

- name: move loki binary
  ansible.builtin.copy:
    src: "/tmp/loki-linux-amd64"
    dest: /opt/loki/loki
    owner: root
    group: root
    mode: 0755
    remote_src: true
  tags:
    - loki
  notify: cleanup installer directory
  changed_when: false

- name: template systemd unit file
  ansible.builtin.template:
    src: templates/loki.service.j2
    dest: /etc/systemd/system/loki.service
    owner: root
    group: root
    mode: 0755
  tags:
    - loki
  changed_when: false

- name: make directory for loki config
  ansible.builtin.file:
    path: /etc/loki
    state: directory
    owner: root
    group: root
    mode: 0644

- name: template loki config file
  ansible.builtin.template:
    src: templates/loki.yml.j2
    dest: /etc/loki/loki.yml
    owner: root
    group: root
    mode: 0644

- name: reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  tags:
    - loki

- name: enable and start loki service
  ansible.builtin.systemd:
    name: loki
    enabled: true
    state: started
  tags:
    - loki
